package uk.co.siland.culvery.core.ui

/**
 * Every Material Symbols glyph the app draws, by ligature name (4c design §3.5). The bundled font holds only these: to
 * add one, add it here and to tools/fonts/icons.txt, then run tools/fonts/subset.py (see tools/fonts/README.md).
 */
object Icons {
    const val ACCOUNT_CIRCLE = "account_circle"
    const val ADD = "add"
    const val ARROW_DOWNWARD = "arrow_downward"
    const val ARROW_UPWARD = "arrow_upward"
    const val BACKSPACE = "backspace"
    const val BEDTIME = "bedtime"
    const val CALENDAR_ADD_ON = "calendar_add_on"
    const val CALENDAR_MONTH = "calendar_month"
    const val CHECK = "check"
    const val CHEVRON_LEFT = "chevron_left"
    const val CHEVRON_RIGHT = "chevron_right"
    const val CLOSE = "close"
    const val CLOUD = "cloud"
    const val CLOUD_OFF = "cloud_off"
    const val CLOUD_UPLOAD = "cloud_upload"
    const val DARK_MODE = "dark_mode"
    const val DATE_RANGE = "date_range"
    const val DELETE = "delete"
    const val DELETE_FOREVER = "delete_forever"
    const val EDIT = "edit"
    const val EDIT_NOTE = "edit_note"
    const val EVENT = "event"
    const val EVENT_AVAILABLE = "event_available"
    const val EVENT_REPEAT = "event_repeat"
    const val EXPAND_LESS = "expand_less"
    const val EXPAND_MORE = "expand_more"
    const val FOGGY = "foggy"
    const val HOME = "home"
    const val INFO = "info"
    const val LIGHT_MODE = "light_mode"
    const val LOCK = "lock"
    const val MOBILE = "mobile"
    const val PARTLY_CLOUDY_DAY = "partly_cloudy_day"
    const val PARTLY_CLOUDY_NIGHT = "partly_cloudy_night"
    const val PERSON = "person"
    const val RAINY = "rainy"
    const val RAINY_HEAVY = "rainy_heavy"
    const val RAINY_LIGHT = "rainy_light"
    const val REFRESH = "refresh"
    const val REPEAT = "repeat"
    const val SCHEDULE = "schedule"
    const val SETTINGS = "settings"
    const val SUNNY = "sunny"
    const val SYNC_PROBLEM = "sync_problem"
    const val THUNDERSTORM = "thunderstorm"
    const val WEATHER_SNOWY = "weather_snowy"
}
